name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build
      run: |
        GOOS=linux GOARCH=amd64 go build -o leetscrape-linux-amd64 ./cmd/leetscrape
        GOOS=windows GOARCH=amd64 go build -o leetscrape-windows-amd64.exe ./cmd/leetscrape
        GOOS=darwin GOARCH=amd64 go build -o leetscrape-darwin-amd64 ./cmd/leetscrape
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release